// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (thread, sender, content)
VALUES ($1, $2, $3)
RETURNING id, thread, sender, content, created_at, updated_at
`

type CreateMessageParams struct {
	Thread  string `json:"thread"`
	Sender  string `json:"sender"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Thread, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Thread,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM message
WHERE id = $1
`

func (q *Queries) DeleteMessageByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessageByID, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, thread, sender, content, created_at, updated_at
FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Thread,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesByThreadPaginated = `-- name: GetMessagesByThreadPaginated :many
SELECT id, thread, sender, content, created_at
FROM message
WHERE thread = $1
ORDER BY created_at ASC
LIMIT $2::int
OFFSET $3::int
`

type GetMessagesByThreadPaginatedParams struct {
	Thread  string `json:"thread"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

type GetMessagesByThreadPaginatedRow struct {
	ID        string           `json:"id"`
	Thread    string           `json:"thread"`
	Sender    string           `json:"sender"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetMessagesByThreadPaginated(ctx context.Context, arg GetMessagesByThreadPaginatedParams) ([]GetMessagesByThreadPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByThreadPaginated, arg.Thread, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByThreadPaginatedRow{}
	for rows.Next() {
		var i GetMessagesByThreadPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Thread,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE message
SET content = $2, updated_at = now()
WHERE id = $1
RETURNING id, thread, sender, content, created_at, updated_at
`

type UpdateMessageContentParams struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Thread,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
