// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    customer_name,
    customer_phone,
    total_amount,
    currency,
    status
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_name, customer_phone, total_amount, currency, status, created_at
`

type CreateOrderParams struct {
	CustomerName  string `json:"customer_name"`
	CustomerPhone string `json:"customer_phone"`
	TotalAmount   int32  `json:"total_amount"`
	Currency      string `json:"currency"`
	Status        string `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.TotalAmount,
		arg.Currency,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_name, customer_phone, total_amount, currency, status, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, customer_name, customer_phone, total_amount, currency, status, created_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
