// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// -- name: CreateThread :one
	// INSERT INTO thread (title)
	// VALUES ($1)
	// RETURNING id, title, created_at;
	// -- name: GetThreadByID :one
	// SELECT id, title, created_at
	// FROM thread
	// WHERE id = $1;
	// -- name: ListThreads :many
	// SELECT id, title, created_at
	// FROM thread
	// ORDER BY created_at DESC;
	CreateThread(ctx context.Context, title string) (Thread, error)
	DeleteMessageByID(ctx context.Context, id string) error
	GetMessageByID(ctx context.Context, id string) (Message, error)
	GetMessagesByThreadPaginated(ctx context.Context, arg GetMessagesByThreadPaginatedParams) ([]GetMessagesByThreadPaginatedRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetThread(ctx context.Context, id string) (Thread, error)
	ListThreads(ctx context.Context) ([]Thread, error)
	UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
