// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thread.sql

package repo

import (
	"context"
)

const createThread = `-- name: CreateThread :one





INSERT INTO thread (title)
VALUES ($1)
RETURNING id, title, created_at
`

// -- name: CreateThread :one
// INSERT INTO thread (title)
// VALUES ($1)
// RETURNING id, title, created_at;
// -- name: GetThreadByID :one
// SELECT id, title, created_at
// FROM thread
// WHERE id = $1;
// -- name: ListThreads :many
// SELECT id, title, created_at
// FROM thread
// ORDER BY created_at DESC;
func (q *Queries) CreateThread(ctx context.Context, title string) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, title)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, title, created_at
FROM thread
WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT id, title, created_at
FROM thread
ORDER BY created_at DESC
`

func (q *Queries) ListThreads(ctx context.Context) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
